"""ToolExecutor — manages the permission → execution → result lifecycle for tool calls."""

import asyncio
import logging
from collections.abc import AsyncGenerator, Callable, Coroutine
from typing import Any

from .audit import AuditLogger
from .context import ToolResultStore
from .events import AgentEvent, PermissionRequest, ToolEnd, ToolStart
from .sandbox import Decision, Sandbox
from .schema import Message, TokenUsage
from .session_memory import SessionMemory
from .tools.base import Tool, ToolResult

logger = logging.getLogger(__name__)

PermissionCallbackType = Callable[[str, dict[str, Any]], Coroutine[Any, Any, bool]]


class ToolExecutor:
    """Manages the lifecycle of tool calls: permission gating, parallel execution, result collection.

    Follows the ToolExecution concept: requested → permitted/denied → executing → succeeded/failed.
    Used by Agent.run_stream() and Agent.execute_plan() to eliminate duplication.
    """

    def __init__(
        self,
        tools: dict[str, Tool],
        sandbox: Sandbox,
        permission_callback: PermissionCallbackType | None = None,
        tool_result_store: ToolResultStore | None = None,
        audit: AuditLogger | None = None,
        session_memory: SessionMemory | None = None,
    ) -> None:
        self.tools = tools
        self.sandbox = sandbox
        self._permission_callback = permission_callback
        self.tool_result_store = tool_result_store
        self._audit = audit
        self._session_memory = session_memory or SessionMemory()
        self._result_messages: list[Message] = []

    @property
    def result_messages(self) -> list[Message]:
        """Messages generated by the last execute_batch call."""
        return self._result_messages

    async def execute_batch(
        self,
        tool_calls: list,
        token_usage: TokenUsage | None = None,
    ) -> AsyncGenerator[AgentEvent, None]:
        """Gate, execute, and collect results for a batch of tool calls.

        Yields PermissionRequest, ToolStart, ToolEnd events.
        Result messages are available via self.result_messages after iteration.
        """
        self._result_messages = []
        tool_tasks: list[tuple[str, str, dict]] = []

        # Phase 1: Permission gating
        for tc in tool_calls:
            tc_id = tc.id
            fn_name = tc.function.name
            args = tc.function.arguments

            decision = self.sandbox.check(fn_name, args)
            logger.debug("Tool %s: sandbox decision=%s", fn_name, decision.value)

            if decision == Decision.DENY:
                async for event in self._deny(tc_id, fn_name,
                    f"Tool blocked by sandbox ({self.sandbox.mode.value} mode): {fn_name}"):
                    yield event
                continue

            if decision == Decision.ASK:
                granted = False
                if self._permission_callback is not None:
                    yield PermissionRequest(tool_call_id=tc_id, tool_name=fn_name, arguments=args)
                    granted = await self._permission_callback(fn_name, args)
                else:
                    logger.warning(
                        "Permission requested for %s but no permission callback is configured; denying.",
                        fn_name,
                    )

                if not granted:
                    error = (
                        f"Permission denied for tool: {fn_name}"
                        if self._permission_callback
                        else "Permission required for tool execution but no prompt handler is configured."
                    )
                    async for event in self._deny(tc_id, fn_name, error):
                        yield event
                    continue

            yield ToolStart(tool_call_id=tc_id, tool_name=fn_name, arguments=args)
            if self._audit:
                self._audit.tool_start(tc_id, fn_name, args)
            tool_tasks.append((tc_id, fn_name, args))

        # Phase 2: Parallel execution
        if not tool_tasks:
            return

        results = await asyncio.gather(
            *(self._execute_one(tc_id, fn, args) for tc_id, fn, args in tool_tasks)
        )

        # Phase 3: Result collection
        args_by_id = {tc_id: args for tc_id, _, args in tool_tasks}
        for tc_id, fn_name, result in results:
            content = result.content if result.success else f"Error: {result.error}"
            if self.tool_result_store and result.success:
                content = self.tool_result_store.store_if_large(content, tc_id)

            if self._session_memory:
                self._session_memory.record_tool_call(
                    fn_name, args_by_id.get(tc_id, {}), content, result.success,
                )

            yield ToolEnd(
                tool_call_id=tc_id,
                tool_name=fn_name,
                success=result.success,
                content=content if result.success else "",
                error=result.error,
            )
            if self._audit:
                self._audit.tool_end(
                    tc_id, fn_name,
                    success=result.success,
                    result_summary=content if result.success else (result.error or ""),
                    error=result.error,
                    token_usage=token_usage.model_dump() if token_usage else None,
                    arguments=args_by_id.get(tc_id),
                )

            self._result_messages.append(Message(
                role="tool", content=content, tool_call_id=tc_id, name=fn_name,
            ))

    async def _deny(self, tc_id: str, fn_name: str, error: str) -> AsyncGenerator[AgentEvent, None]:
        """Record a denied tool call."""
        yield ToolEnd(tool_call_id=tc_id, tool_name=fn_name, success=False, content="", error=error)
        self._result_messages.append(Message(
            role="tool", content=f"Error: {error}", tool_call_id=tc_id, name=fn_name,
        ))

    async def _execute_one(self, tc_id: str, fn_name: str, args: dict) -> tuple[str, str, ToolResult]:
        """Execute a single tool call."""
        if fn_name not in self.tools:
            return tc_id, fn_name, ToolResult(success=False, content="", error=f"Unknown tool: {fn_name}")
        try:
            return tc_id, fn_name, await self.tools[fn_name].execute(**args)
        except Exception as e:
            return tc_id, fn_name, ToolResult(success=False, content="", error=f"Tool execution failed: {e}")
